[build-system]
requires = ["setuptools>=68.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyWaveRecipe"
version = "0.0.23"
requires-python = ">=3.11"
readme = "README.md"
license = {file = "LICENSE"}